# Generated by Django 6.0.1 on 2026-06-02 16:33

import applications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_application_digital_signature'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=applications.models.certificate_upload_path),
        ),
    ]
